// Assessment Phases and Tasks for ZTMM Assessment
// Provides a structured workflow for assessors

export type TaskStatus = 'not_started' | 'in_progress' | 'completed' | 'skipped';
export type TaskPriority = 'required' | 'recommended' | 'optional';

export interface AssessmentTask {
  id: string;
  title: string;
  description: string;
  priority: TaskPriority;
  estimatedMinutes: number;
  tips?: string[];
  steps?: string[]; // Step-by-step guidance to complete the task
  acceptanceCriteria?: string[]; // What needs to be true for the task to be considered done
  subtasks?: { id: string; title: string }[]; // Optional finer-grain checklist
  deliverables?: string[];
  relatedPillar?: string;
}

export interface AssessmentPhase {
  id: string;
  number: number;
  name: string;
  description: string;
  objectives: string[];
  estimatedDays: string;
  tasks: AssessmentTask[];
  keyDeliverables: string[];
  successCriteria: string[];
}

export const assessmentPhases: AssessmentPhase[] = [
  {
    id: 'preparation',
    number: 0,
    name: 'Preparation',
    description: 'Establish the foundation for a successful assessment by defining scope, identifying stakeholders, and gathering preliminary information.',
    objectives: [
      'Define assessment scope and boundaries',
      'Identify key stakeholders and their roles',
      'Gather existing documentation and policies',
      'Establish communication channels and schedule',
    ],
    estimatedDays: '3-5 days',
    keyDeliverables: [
      'Assessment charter/scope document',
      'Stakeholder register with RACI matrix',
      'Document inventory checklist',
      'Assessment schedule and timeline',
    ],
    successCriteria: [
      'Executive sponsor identified and engaged',
      'Assessment scope approved by stakeholders',
      'Initial document collection completed',
      'Kickoff meeting scheduled',
    ],
    tasks: [
      {
        id: 'prep-1',
        title: 'Identify Executive Sponsor',
        description: 'Identify and engage an executive sponsor who will champion the Zero Trust initiative and provide necessary authority and resources.',
        priority: 'required',
        estimatedMinutes: 60,
        tips: [
          'Look for C-level or VP-level sponsor with security/IT authority',
          'Ensure sponsor understands Zero Trust benefits and commitment required',
          'Document sponsor\'s expectations and success criteria',
        ],
        steps: [
          'Review organization chart and identify potential sponsors',
          'Reach out with assessment overview and ask for sponsorship',
          'Schedule a short alignment meeting to confirm expectations and resources',
          'Document the sponsor contact and signed approval for assessment scope',
        ],
        acceptanceCriteria: [
          'Sponsor has acknowledged the assessment scope and timeline',
          'Sponsor committed resources and points of contact',
        ],
        deliverables: ['Executive sponsor name and contact', 'Sponsor commitment confirmation'],
      },
      {
        id: 'prep-2',
        title: 'Define Assessment Scope',
        description: 'Clearly define what systems, applications, users, and data will be included in the assessment. Document any exclusions.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Start with critical business systems and high-value assets',
          'Consider regulatory requirements (HIPAA, PCI-DSS, etc.)',
          'Document any systems explicitly excluded and reasons',
          'Include cloud, on-premises, and hybrid environments',
        ],
        steps: [
          'Schedule a scoping workshop with business and IT stakeholders',
          'List all systems and data types in-scope and out-of-scope',
          'Identify environment owners and SMEs for each system',
          'Get formal approval on the scope document from the sponsor',
        ],
        acceptanceCriteria: [
          'Scope document is signed-off by sponsor and key stakeholders',
          'System inventory for in-scope assets is complete',
        ],
        deliverables: ['Scope document', 'System inventory list', 'Exclusion list with justifications'],
      },
      {
        id: 'prep-3',
        title: 'Identify Key Stakeholders',
        description: 'Create a comprehensive list of stakeholders who should be involved in the assessment process.',
        priority: 'required',
        estimatedMinutes: 90,
        tips: [
          'Include IT, Security, Compliance, Legal, and Business units',
          'Identify subject matter experts for each pillar',
          'Document decision-makers vs. contributors',
          'Consider external stakeholders (vendors, partners)',
        ],
        steps: [
          'Run a stakeholder brainstorming session with project team',
          'Map stakeholders to business capabilities and systems',
          'Assign RACI roles where appropriate',
          'Validate the list and contact information with the sponsor',
        ],
        acceptanceCriteria: [
          'Stakeholder register includes names, roles, and contact details for required SMEs',
          'RACI matrix is populated and approved by sponsor',
        ],
        deliverables: ['Stakeholder register', 'Contact list', 'RACI matrix'],
      },
      {
        id: 'prep-4',
        title: 'Gather Existing Documentation',
        description: 'Collect all relevant security policies, architecture diagrams, and compliance documentation.',
        priority: 'required',
        estimatedMinutes: 180,
        tips: [
          'Request network architecture diagrams',
          'Collect identity and access management policies',
          'Gather recent audit reports and findings',
          'Include incident response plans and procedures',
        ],
        deliverables: ['Document inventory', 'Gap list for missing documents'],
      },
      {
        id: 'prep-5',
        title: 'Create Assessment Schedule',
        description: 'Develop a detailed schedule for the assessment including interviews, workshops, and review sessions.',
        priority: 'required',
        estimatedMinutes: 60,
        tips: [
          'Allow buffer time for rescheduling',
          'Group related interviews together',
          'Schedule executive briefings at key milestones',
          'Consider stakeholder availability and time zones',
        ],
        deliverables: ['Assessment timeline', 'Interview schedule', 'Milestone calendar'],
      },
      {
        id: 'prep-6',
        title: 'Conduct Kickoff Meeting',
        description: 'Hold a kickoff meeting with all stakeholders to align on objectives, scope, and expectations.',
        priority: 'required',
        estimatedMinutes: 90,
        tips: [
          'Prepare presentation covering Zero Trust basics',
          'Review assessment methodology and timeline',
          'Address questions and concerns',
          'Confirm stakeholder commitments',
        ],
        deliverables: ['Kickoff presentation', 'Meeting minutes', 'Action items list'],
      },
      {
        id: 'prep-7',
        title: 'Set Up Assessment Tools',
        description: 'Configure assessment tools, templates, and collaboration spaces for the assessment team.',
        priority: 'recommended',
        estimatedMinutes: 60,
        tips: [
          'Set up shared document repository',
          'Configure this assessment tool with project details',
          'Create interview templates and questionnaires',
          'Establish secure communication channels',
        ],
        deliverables: ['Configured assessment environment', 'Template library'],
      },
    ],
  },
  {
    id: 'discovery',
    number: 1,
    name: 'Discovery & Current State',
    description: 'Gather detailed information about the current security posture, existing controls, and technology landscape.',
    objectives: [
      'Document current security architecture',
      'Inventory existing security controls and tools',
      'Understand current identity and access management',
      'Map data flows and network architecture',
    ],
    estimatedDays: '5-10 days',
    keyDeliverables: [
      'Current state architecture diagrams',
      'Security controls inventory',
      'Technology stack documentation',
      'Interview findings summary',
    ],
    successCriteria: [
      'All pillar SME interviews completed',
      'Current architecture documented',
      'Security tools inventory complete',
      'Data flow diagrams created',
    ],
    tasks: [
      {
        id: 'disc-1',
        title: 'Conduct Identity SME Interviews',
        description: 'Interview subject matter experts responsible for identity and access management.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'identity',
        tips: [
          'Cover authentication methods (MFA, SSO, passwordless)',
          'Discuss identity lifecycle management',
          'Review privileged access management',
          'Understand federation and external identity needs',
        ],
        steps: [
          'Prepare interview questionnaire focusing on authentication, provisioning, and PAM',
          'Schedule 60-90 minute sessions with identity SMEs',
          'Record responses and map to existing identity systems',
          'Validate answers with evidence (policy documents, configurations, screenshots)',
        ],
        acceptanceCriteria: [
          'All identity SMEs interviewed',
          'Interview notes captured and uploaded',
          'Key identity controls documented with evidence',
        ],
        deliverables: ['Identity interview notes', 'Current state findings'],
      },
      {
        id: 'disc-2',
        title: 'Conduct Device/Endpoint SME Interviews',
        description: 'Interview teams responsible for endpoint management and device security.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'devices',
        tips: [
          'Cover device inventory and management tools',
          'Discuss BYOD and mobile device policies',
          'Review endpoint protection solutions',
          'Understand device compliance enforcement',
        ],
        steps: [
          'Prepare questionnaire on device inventory, EDR, MDM/UEM, and compliance',
          'Schedule interviews with endpoint and device owners',
          'Collect evidence: EDR console screenshots, device inventory export',
          'Summarize findings and map gaps to device controls',
        ],
        acceptanceCriteria: [
          'Endpoint inventory collected and validated',
          'EDR/MDM coverage documented',
          'Risks and gaps recorded with supporting evidence',
        ],
        deliverables: ['Device interview notes', 'Endpoint inventory'],
      },
      {
        id: 'disc-3',
        title: 'Conduct Network SME Interviews',
        description: 'Interview network and infrastructure teams about network architecture and security.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'networks',
        tips: [
          'Review network segmentation approach',
          'Discuss encryption standards (in-transit, at-rest)',
          'Understand DNS security and filtering',
          'Cover remote access and VPN solutions',
        ],
        deliverables: ['Network interview notes', 'Network diagrams'],
      },
      {
        id: 'disc-4',
        title: 'Conduct Application SME Interviews',
        description: 'Interview application and development teams about application security practices.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'applications',
        tips: [
          'Cover application inventory and classification',
          'Discuss secure development practices (DevSecOps)',
          'Review application access controls',
          'Understand API security measures',
        ],
        deliverables: ['Application interview notes', 'Application inventory'],
      },
      {
        id: 'disc-5',
        title: 'Conduct Data Security SME Interviews',
        description: 'Interview data governance and security teams about data protection practices.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'data',
        tips: [
          'Cover data classification and inventory',
          'Discuss data loss prevention (DLP) controls',
          'Review encryption and key management',
          'Understand data access controls and monitoring',
        ],
        deliverables: ['Data security interview notes', 'Data classification overview'],
      },
      {
        id: 'disc-6',
        title: 'Conduct Security Operations Interviews',
        description: 'Interview SOC and security operations teams about monitoring and response capabilities.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'visibility',
        tips: [
          'Cover SIEM and logging infrastructure',
          'Discuss threat detection capabilities',
          'Review incident response procedures',
          'Understand security metrics and reporting',
        ],
        deliverables: ['SecOps interview notes', 'Tool inventory'],
      },
      {
        id: 'disc-7',
        title: 'Review Existing Security Policies',
        description: 'Analyze existing security policies and standards for Zero Trust alignment.',
        priority: 'required',
        estimatedMinutes: 180,
        tips: [
          'Review access control policies',
          'Analyze authentication requirements',
          'Check encryption standards',
          'Evaluate compliance requirements',
        ],
        deliverables: ['Policy review findings', 'Gap analysis'],
      },
      {
        id: 'disc-8',
        title: 'Document Current Architecture',
        description: 'Create or update architecture diagrams showing current security controls and data flows.',
        priority: 'required',
        estimatedMinutes: 240,
        tips: [
          'Include network topology and segmentation',
          'Show identity and access flows',
          'Document data flows and storage locations',
          'Highlight security control points',
        ],
        deliverables: ['Architecture diagrams', 'Data flow diagrams'],
      },
      {
        id: 'disc-9',
        title: 'Inventory Security Tools',
        description: 'Create a comprehensive inventory of all security tools and technologies in use.',
        priority: 'recommended',
        estimatedMinutes: 120,
        tips: [
          'Include vendor, version, and coverage',
          'Note integration points between tools',
          'Identify gaps and overlaps',
          'Document licensing and support status',
        ],
        deliverables: ['Security tools inventory spreadsheet'],
      },
      {
        id: 'disc-10',
        title: 'Review Recent Audit Findings',
        description: 'Analyze recent internal and external audit findings related to security.',
        priority: 'recommended',
        estimatedMinutes: 90,
        tips: [
          'Review findings from compliance audits',
          'Check penetration test results',
          'Analyze vulnerability assessment reports',
          'Note remediation status of findings',
        ],
        deliverables: ['Audit findings summary', 'Open items list'],
      },
    ],
  },
  {
    id: 'assessment',
    number: 2,
    name: 'Pillar Assessment',
    description: 'Conduct detailed assessment of each Zero Trust pillar using the CISA ZTMM framework.',
    objectives: [
      'Assess maturity level for each pillar',
      'Document evidence for maturity ratings',
      'Identify gaps and improvement opportunities',
      'Validate findings with stakeholders',
    ],
    estimatedDays: '10-15 days',
    keyDeliverables: [
      'Completed pillar assessments',
      'Evidence documentation',
      'Maturity ratings with justification',
      'Gap identification report',
    ],
    successCriteria: [
      'All pillar questions answered',
      'Evidence collected for each rating',
      'Findings validated by SMEs',
      'Initial maturity scores calculated',
    ],
    tasks: [
      {
        id: 'assess-1',
        title: 'Complete Identity Pillar Assessment',
        description: 'Assess all Identity pillar functions: Authentication, Identity Stores, Risk Assessment, Access Management, and Federation.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'identity',
        tips: [
          'Use interview findings as input',
          'Request evidence for each maturity claim',
          'Consider both technical and process maturity',
          'Document specific gaps and recommendations',
        ],
        deliverables: ['Identity pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-2',
        title: 'Complete Devices Pillar Assessment',
        description: 'Assess all Devices pillar functions: Asset Inventory, Device Compliance, Threat Protection, and Policy Enforcement.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'devices',
        tips: [
          'Verify device inventory completeness',
          'Test compliance enforcement mechanisms',
          'Review EDR/XDR capabilities',
          'Check BYOD and IoT coverage',
        ],
        deliverables: ['Devices pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-3',
        title: 'Complete Networks Pillar Assessment',
        description: 'Assess all Networks pillar functions: Segmentation, Traffic Management, Encryption, and Network Visibility.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'networks',
        tips: [
          'Review network architecture diagrams',
          'Verify micro-segmentation implementation',
          'Check encryption standards compliance',
          'Assess east-west traffic controls',
        ],
        deliverables: ['Networks pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-4',
        title: 'Complete Applications Pillar Assessment',
        description: 'Assess all Applications pillar functions: Application Inventory, Access Control, Threat Protection, and Secure Development.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'applications',
        tips: [
          'Review application inventory and classification',
          'Check application-level access controls',
          'Assess DevSecOps practices',
          'Verify API security measures',
        ],
        deliverables: ['Applications pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-5',
        title: 'Complete Data Pillar Assessment',
        description: 'Assess all Data pillar functions: Data Inventory, Data Classification, Data Protection, and Data Access.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'data',
        tips: [
          'Verify data classification scheme',
          'Check DLP implementation',
          'Review encryption and key management',
          'Assess data access controls',
        ],
        deliverables: ['Data pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-6',
        title: 'Complete Visibility & Analytics Pillar Assessment',
        description: 'Assess logging, monitoring, threat detection, and security analytics capabilities.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'visibility',
        tips: [
          'Review SIEM coverage and retention',
          'Check threat detection capabilities',
          'Assess security metrics and dashboards',
          'Verify log aggregation completeness',
        ],
        deliverables: ['Visibility pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-7',
        title: 'Complete Automation & Orchestration Pillar Assessment',
        description: 'Assess security automation, orchestration, and response capabilities.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'automation',
        tips: [
          'Review SOAR implementation',
          'Check automated response playbooks',
          'Assess policy automation capabilities',
          'Verify integration between security tools',
        ],
        deliverables: ['Automation pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-8',
        title: 'Complete Governance Pillar Assessment',
        description: 'Assess governance, risk management, and compliance capabilities related to Zero Trust.',
        priority: 'required',
        estimatedMinutes: 180,
        relatedPillar: 'governance',
        tips: [
          'Review Zero Trust strategy and roadmap',
          'Check policy framework completeness',
          'Assess risk management integration',
          'Verify compliance monitoring',
        ],
        deliverables: ['Governance pillar assessment', 'Evidence artifacts'],
      },
      {
        id: 'assess-9',
        title: 'Validate Findings with SMEs',
        description: 'Review assessment findings with subject matter experts to ensure accuracy.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Schedule validation sessions for each pillar',
          'Present findings and evidence',
          'Address disagreements with additional evidence',
          'Document any rating adjustments',
        ],
        deliverables: ['Validated assessment findings', 'SME sign-off'],
      },
      {
        id: 'assess-10',
        title: 'Document Evidence Repository',
        description: 'Organize and document all evidence collected during the assessment.',
        priority: 'recommended',
        estimatedMinutes: 120,
        tips: [
          'Create consistent naming convention',
          'Link evidence to specific questions',
          'Include screenshots and configurations',
          'Maintain chain of custody for sensitive items',
        ],
        deliverables: ['Evidence repository', 'Evidence index'],
      },
    ],
  },
  {
    id: 'analysis',
    number: 3,
    name: 'Analysis & Gap Assessment',
    description: 'Analyze assessment results, identify gaps, and prioritize improvement opportunities.',
    objectives: [
      'Calculate final maturity scores',
      'Identify critical gaps and risks',
      'Prioritize improvement opportunities',
      'Develop target state recommendations',
    ],
    estimatedDays: '5-7 days',
    keyDeliverables: [
      'Maturity score report',
      'Gap analysis document',
      'Risk-prioritized findings',
      'Target state definition',
    ],
    successCriteria: [
      'All pillar scores finalized',
      'Gaps mapped to business risks',
      'Quick wins identified',
      'Target maturity levels defined',
    ],
    tasks: [
      {
        id: 'analysis-1',
        title: 'Calculate Final Maturity Scores',
        description: 'Finalize maturity scores for each pillar and calculate overall organizational maturity.',
        priority: 'required',
        estimatedMinutes: 90,
        tips: [
          'Use weighted scoring if applicable',
          'Document scoring methodology',
          'Compare against industry benchmarks',
          'Identify lowest-scoring areas',
        ],
        deliverables: ['Final maturity scorecard', 'Scoring methodology document'],
      },
      {
        id: 'analysis-2',
        title: 'Perform Gap Analysis',
        description: 'Identify gaps between current state and target Zero Trust maturity levels.',
        priority: 'required',
        estimatedMinutes: 180,
        tips: [
          'Define target maturity for each pillar',
          'Quantify gaps in measurable terms',
          'Consider dependencies between pillars',
          'Identify cross-cutting gaps',
        ],
        deliverables: ['Gap analysis report', 'Gap heat map'],
      },
      {
        id: 'analysis-3',
        title: 'Map Gaps to Business Risks',
        description: 'Connect identified gaps to specific business and security risks.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Use risk scoring methodology',
          'Consider likelihood and impact',
          'Reference threat intelligence',
          'Align with enterprise risk framework',
        ],
        deliverables: ['Risk mapping document', 'Risk register updates'],
      },
      {
        id: 'analysis-4',
        title: 'Identify Quick Wins',
        description: 'Identify low-effort, high-impact improvements that can be implemented quickly.',
        priority: 'required',
        estimatedMinutes: 90,
        tips: [
          'Look for configuration changes',
          'Identify unused tool capabilities',
          'Find policy enforcement gaps',
          'Consider training opportunities',
        ],
        deliverables: ['Quick wins list', 'Implementation estimates'],
      },
      {
        id: 'analysis-5',
        title: 'Define Target State Architecture',
        description: 'Document the target Zero Trust architecture and maturity levels.',
        priority: 'required',
        estimatedMinutes: 180,
        tips: [
          'Align with CISA ZTMM guidance',
          'Consider organizational constraints',
          'Define phased approach',
          'Include technology requirements',
        ],
        deliverables: ['Target state architecture', 'Technology requirements'],
      },
      {
        id: 'analysis-6',
        title: 'Prioritize Improvement Initiatives',
        description: 'Rank improvement initiatives based on risk reduction, effort, and dependencies.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Use prioritization matrix',
          'Consider resource constraints',
          'Account for dependencies',
          'Balance quick wins with strategic initiatives',
        ],
        deliverables: ['Prioritized initiative list', 'Prioritization rationale'],
      },
      {
        id: 'analysis-7',
        title: 'Estimate Resource Requirements',
        description: 'Estimate budget, staffing, and timeline for recommended improvements.',
        priority: 'recommended',
        estimatedMinutes: 180,
        tips: [
          'Include technology costs',
          'Consider implementation services',
          'Account for training needs',
          'Plan for ongoing operations',
        ],
        deliverables: ['Resource estimates', 'Budget projections'],
      },
      {
        id: 'analysis-8',
        title: 'Identify Dependencies and Prerequisites',
        description: 'Map dependencies between initiatives and identify prerequisites.',
        priority: 'recommended',
        estimatedMinutes: 90,
        tips: [
          'Create dependency diagram',
          'Identify blocking items',
          'Note external dependencies',
          'Consider organizational readiness',
        ],
        deliverables: ['Dependency map', 'Prerequisites list'],
      },
    ],
  },
  {
    id: 'recommendations',
    number: 4,
    name: 'Roadmap Development',
    description: 'Develop a comprehensive Zero Trust implementation roadmap with actionable recommendations.',
    objectives: [
      'Create phased implementation roadmap',
      'Define specific recommendations for each pillar',
      'Establish success metrics and KPIs',
      'Develop business case for investment',
    ],
    estimatedDays: '5-7 days',
    keyDeliverables: [
      'Zero Trust implementation roadmap',
      'Detailed recommendations document',
      'Success metrics and KPIs',
      'Business case presentation',
    ],
    successCriteria: [
      'Roadmap approved by stakeholders',
      'Recommendations are actionable',
      'Metrics defined for each initiative',
      'Business case accepted',
    ],
    tasks: [
      {
        id: 'road-1',
        title: 'Develop Phased Roadmap',
        description: 'Create a multi-phase roadmap for Zero Trust implementation over 12-36 months.',
        priority: 'required',
        estimatedMinutes: 240,
        tips: [
          'Define 3-4 implementation phases',
          'Align phases with budget cycles',
          'Include milestones and checkpoints',
          'Build in flexibility for adjustments',
        ],
        deliverables: ['Implementation roadmap', 'Phase definitions'],
      },
      {
        id: 'road-2',
        title: 'Write Identity Pillar Recommendations',
        description: 'Develop specific, actionable recommendations for improving Identity maturity.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'identity',
        tips: [
          'Address MFA and passwordless authentication',
          'Include identity governance improvements',
          'Cover privileged access management',
          'Consider identity federation needs',
        ],
        deliverables: ['Identity recommendations document'],
      },
      {
        id: 'road-3',
        title: 'Write Devices Pillar Recommendations',
        description: 'Develop specific, actionable recommendations for improving Devices maturity.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'devices',
        tips: [
          'Address device inventory gaps',
          'Include compliance enforcement improvements',
          'Cover EDR/XDR enhancements',
          'Consider BYOD and IoT strategies',
        ],
        deliverables: ['Devices recommendations document'],
      },
      {
        id: 'road-4',
        title: 'Write Networks Pillar Recommendations',
        description: 'Develop specific, actionable recommendations for improving Networks maturity.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'networks',
        tips: [
          'Address micro-segmentation strategy',
          'Include encryption improvements',
          'Cover ZTNA implementation',
          'Consider SD-WAN and SASE options',
        ],
        deliverables: ['Networks recommendations document'],
      },
      {
        id: 'road-5',
        title: 'Write Applications Pillar Recommendations',
        description: 'Develop specific, actionable recommendations for improving Applications maturity.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'applications',
        tips: [
          'Address application inventory gaps',
          'Include DevSecOps improvements',
          'Cover API security enhancements',
          'Consider application access controls',
        ],
        deliverables: ['Applications recommendations document'],
      },
      {
        id: 'road-6',
        title: 'Write Data Pillar Recommendations',
        description: 'Develop specific, actionable recommendations for improving Data maturity.',
        priority: 'required',
        estimatedMinutes: 120,
        relatedPillar: 'data',
        tips: [
          'Address data classification gaps',
          'Include DLP improvements',
          'Cover encryption enhancements',
          'Consider data access governance',
        ],
        deliverables: ['Data recommendations document'],
      },
      {
        id: 'road-7',
        title: 'Define Success Metrics and KPIs',
        description: 'Establish measurable metrics to track Zero Trust implementation progress.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Define metrics for each pillar',
          'Include leading and lagging indicators',
          'Set realistic targets',
          'Plan for metric collection',
        ],
        deliverables: ['KPI definitions', 'Metrics dashboard design'],
      },
      {
        id: 'road-8',
        title: 'Develop Business Case',
        description: 'Create a compelling business case for Zero Trust investment.',
        priority: 'required',
        estimatedMinutes: 180,
        tips: [
          'Quantify risk reduction benefits',
          'Include compliance benefits',
          'Calculate ROI where possible',
          'Address operational efficiencies',
        ],
        deliverables: ['Business case document', 'ROI analysis'],
      },
      {
        id: 'road-9',
        title: 'Create Implementation Playbooks',
        description: 'Develop detailed playbooks for key implementation initiatives.',
        priority: 'recommended',
        estimatedMinutes: 240,
        tips: [
          'Include step-by-step guidance',
          'Define roles and responsibilities',
          'Include testing and validation steps',
          'Add rollback procedures',
        ],
        deliverables: ['Implementation playbooks'],
      },
    ],
  },
  {
    id: 'reporting',
    number: 5,
    name: 'Reporting & Handoff',
    description: 'Compile final reports, present findings to stakeholders, and transition to implementation.',
    objectives: [
      'Compile comprehensive assessment report',
      'Present findings to executive leadership',
      'Obtain stakeholder approval',
      'Transition to implementation team',
    ],
    estimatedDays: '3-5 days',
    keyDeliverables: [
      'Executive summary report',
      'Detailed assessment report',
      'Executive presentation',
      'Implementation handoff package',
    ],
    successCriteria: [
      'Reports delivered and accepted',
      'Executive presentation completed',
      'Roadmap approved for implementation',
      'Implementation team briefed',
    ],
    tasks: [
      {
        id: 'report-1',
        title: 'Compile Executive Summary',
        description: 'Create a concise executive summary highlighting key findings and recommendations.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Keep to 2-3 pages maximum',
          'Lead with key findings',
          'Include maturity scores visual',
          'Highlight top recommendations',
        ],
        deliverables: ['Executive summary document'],
      },
      {
        id: 'report-2',
        title: 'Compile Detailed Assessment Report',
        description: 'Create comprehensive report with all findings, evidence, and recommendations.',
        priority: 'required',
        estimatedMinutes: 240,
        tips: [
          'Include methodology section',
          'Document all pillar assessments',
          'Add evidence references',
          'Include appendices for details',
        ],
        deliverables: ['Detailed assessment report'],
      },
      {
        id: 'report-3',
        title: 'Create Executive Presentation',
        description: 'Develop presentation for executive leadership briefing.',
        priority: 'required',
        estimatedMinutes: 180,
        tips: [
          'Focus on business impact',
          'Use visuals and charts',
          'Prepare for Q&A',
          'Include clear ask/next steps',
        ],
        deliverables: ['Executive presentation deck'],
      },
      {
        id: 'report-4',
        title: 'Conduct Executive Briefing',
        description: 'Present findings and recommendations to executive leadership.',
        priority: 'required',
        estimatedMinutes: 90,
        tips: [
          'Practice presentation',
          'Anticipate questions',
          'Have backup slides ready',
          'Document decisions and feedback',
        ],
        deliverables: ['Meeting minutes', 'Decision log'],
      },
      {
        id: 'report-5',
        title: 'Obtain Stakeholder Sign-off',
        description: 'Get formal approval of assessment findings and roadmap.',
        priority: 'required',
        estimatedMinutes: 60,
        tips: [
          'Circulate final documents',
          'Address any final concerns',
          'Document approvals',
          'Set implementation kickoff date',
        ],
        deliverables: ['Signed approval document'],
      },
      {
        id: 'report-6',
        title: 'Create Implementation Handoff Package',
        description: 'Prepare all materials needed for implementation team.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Include all assessment artifacts',
          'Add contact information',
          'Document assumptions and constraints',
          'Include lessons learned',
        ],
        deliverables: ['Handoff package', 'Knowledge transfer document'],
      },
      {
        id: 'report-7',
        title: 'Conduct Implementation Team Briefing',
        description: 'Brief the implementation team on assessment findings and roadmap.',
        priority: 'required',
        estimatedMinutes: 120,
        tips: [
          'Walk through key findings',
          'Explain prioritization rationale',
          'Discuss dependencies',
          'Answer questions',
        ],
        deliverables: ['Briefing notes', 'Q&A log'],
      },
      {
        id: 'report-8',
        title: 'Schedule Follow-up Assessment',
        description: 'Plan for periodic reassessment to track progress.',
        priority: 'recommended',
        estimatedMinutes: 30,
        tips: [
          'Recommend 6-12 month intervals',
          'Define reassessment scope',
          'Identify metrics to track',
          'Set calendar reminders',
        ],
        deliverables: ['Reassessment schedule'],
      },
    ],
  },
];

export const getPhaseById = (phaseId: string): AssessmentPhase | undefined => {
  return assessmentPhases.find(p => p.id === phaseId);
};

export const getTotalTasks = (): number => {
  return assessmentPhases.reduce((sum, phase) => sum + phase.tasks.length, 0);
};

export const getRequiredTasks = (): AssessmentTask[] => {
  return assessmentPhases.flatMap(phase => 
    phase.tasks.filter(task => task.priority === 'required')
  );
};

export const getTasksByPillar = (pillarId: string): AssessmentTask[] => {
  return assessmentPhases.flatMap(phase =>
    phase.tasks.filter(task => task.relatedPillar === pillarId)
  );
};
